// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DocuGen
{
    internal sealed partial class Vsix
    {
        public const string Id = "DocuGen.15023a3a-0552-4ed9-b17b-630cedf5e099";
        public const string Name = "DocuGen";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Karan Valecha";
        public const string Tags = "";
    }
}
