// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DocuGen_CommunityToolkit
{
    internal sealed partial class Vsix
    {
        public const string Id = "DocuGen_CommunityToolkit.b21bd79a-1bfe-48e4-b297-4cd5eb5e7405";
        public const string Name = "DocuGen_CommunityToolkit";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Karan Valecha";
        public const string Tags = "";
    }
}
