// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DocuGen_CommunityToolkit
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string DocuGenString = "104ba460-e88f-4cb3-943f-98971ee6c1a6";
        public static Guid DocuGen = new Guid(DocuGenString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int DocuGenMenuGroup = 0x0001;
        public const int DocuGenCommand = 0x0100;
    }
}