name: Run latest-tag

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  latest-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          description: 'Docugen AI'
          force-branch: true
          ref: 'latest' # You can change this to any custom tag name if needed
